name: BotBlocker
main: ovh.aichan.botblockerminecraft.BotBlocker
version: 1.4.0
api-version: '1.20'
author: aichan
description: A plugin to ban users who connect for the first time and disconnect within a certain time limit.

permissions:
  botblocker.enable:
    description: Allows the user to enable the BotBlocker plugin.
    default: op
  botblocker.disable:
    description: Allows the user to disable the BotBlocker plugin.
    default: op
  botblocker.status:
    description: Allows the user to see whether BotBlocker is enabled or disabled.
    default: true
  botblocker.settimelimit:
    description: Allows the user to set the time limit for detecting bots.
    default: op
  botblocker.gettimelimit:
    description: Allows the user to display the configured time limit for detecting bots.
    default: true
  botblocker.setbanmessage:
    description: Allows the user to set the ban message.
    default: op
  botblocker.getbanmessage:
    description: Allows the user to display the configured ban message.
    default: true

commands:
  botblocker:
    description: Manages the BotBlocker plugin
    usage: |
      /<command> enable - Enable the BotBlocker plugin.
      /<command> disable - Disable the BotBlocker plugin.
      /<command> status - Show wether BotBlocker is enabled or disabled.
      /<command> setTimeLimit [seconds] - Set the time limit for detecting bots. Default is 5 seconds.
      /<command> getTimeLimit - Display the configured time limit for detecting bots.
      /<command> setBanMessage [message] - Set the ban message.
      /<command> getBanMessage - Display the configured ban message.
